#echo "---------------------------------------------------------------"
#echo "All processes"
#echo "---------------------------------------------------------------"
#ps -axo pid,pcpu,nlwp,vsz,rss,command | grep -v "grep"
echo "---------------------------------------------------------------"
echo "PGSQL"
echo "---------------------------------------------------------------"
ps -axo pid,pcpu,nlwp,vsz,rss,command | grep "PID\|postgres" | grep -v "grep"
echo "---------------------------------------------------------------"
echo "Perl"
echo "---------------------------------------------------------------"
ps -axo pid,pcpu,nlwp,vsz,rss,command | grep "PID\|perl" | grep -v "grep"
echo "---------------------------------------------------------------"
echo "Apache"
echo "---------------------------------------------------------------"
ps -axo pid,pcpu,nlwp,vsz,rss,command | grep "PID\|httpd" | grep -v "grep"
